version: "3.7"


services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    restart: always
    environment:
      - "ALLOW_ANONYMOUS_LOGIN=yes"

  kafka:
    image: docker.io/bitnami/kafka:3
    restart: always
    environment:
      - "KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "ALLOW_PLAINTEXT_LISTENER=yes"
    depends_on:
      - zookeeper

  clickhouse:
    build:
      dockerfile: clickhouse.Dockerfile
      context: ./services
    restart: always
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - kafka
    environment:
      - "KAFKA_DSN=kafka:9092"
      - "KAFKA_CH_TOPIC=db"

  kafka-ui:
    image: provectuslabs/kafka-ui
    restart: always
    ports:
      - "9011:8080"
    environment:
      - "KAFKA_CLUSTERS_0_NAME=local"
      - "KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092"
      - "KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181"
    depends_on:
      - kafka

  generator:
    build:
      dockerfile: services.Dockerfile
      context: ./services
    restart: always
    environment:
      - "KAFKA_DSN=kafka:9092"
      - "KAFKA_CH_TOPIC=db"
      - "SYMBOLS_COUNT=100"
    command:
      - "python"
      - "-m"
      - "generator"
    depends_on:
      - kafka

  service:
    build:
      dockerfile: services.Dockerfile
      context: ./services
    restart: always
    environment:
      - "KAFKA_DSN=kafka:9092"
      - "SYMBOLS_COUNT=100"
    command:
      - "uvicorn"
      - "service:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "80"
    depends_on:
      - kafka
      - clickhouse

  dashboard:
    build:
      dockerfile: Dockerfile
      context: ./dashboard
    restart: always
    ports:
      - "9010:80"
    depends_on:
      - service
      - kafka-ui